SemesterProject-CSS-1/config/routes.rb
Rails.application.routes.draw do
  resources :sales
  resources :customers
  resources :quotes
  resources :employees
  resources :employees
  resources :inventories

  root 'employees#index'

end

SemesterProject-CSS-1/app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :customer
  has_many :quotes
end

SemesterProject-CSS-1/app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:quote, :dealer_price, :sales_tax, :sale_total_amount, :sale_date)
    end
end

SemesterProject-CSS-1/app/helpers/sales_helper.rb
module SalesHelper
end

SemesterProject-CSS-1/app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quote %><br>
    <%= f.collection_select :quote, Quote.all, :id, :quote_info %>
  </div>
  <div class="field">
    <%= f.label :dealer_price %><br>
    <%= f.text_field :dealer_price %>
  </div>
  <div class="field">
    <%= f.label :sales_tax %><br>
    <%= f.text_field :sales_tax %>
  </div>
  <div class="field">
    <%= f.label :sale_total_amount %><br>
    <%= f.text_field :sale_total_amount %>
  </div>
  <div class="field">
    <%= f.label :sale_date %><br>
    <%= f.date_select :sale_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SemesterProject-CSS-1/app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

SemesterProject-CSS-1/app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sales</h1>

<table>
  <thead>
    <tr>
      <th>Quote</th>
      <th>Dealer price</th>
      <th>Sales tax</th>
      <th>Sale total amount</th>
      <th>Sale date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.quote.quote_info %></td>
        <td><%= number_to_currency(sale.dealer_price) %></td>
        <td><%= number_to_currency(sale.sales_tax) %></td>
        <td><%= number_to_currency(sale.sale_total_amount) %></td>
        <td><%= sale.sale_date %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>

SemesterProject-CSS-1/app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

SemesterProject-CSS-1/app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quote:</strong>
  <%= @sale.quote.quote_info %>
</p>

<p>
  <strong>Dealer price:</strong>
  <%= @sale.dealer_price %>
</p>

<p>
  <strong>Sales tax:</strong>
  <%= @sale.sales_tax %>
</p>

<p>
  <strong>Sale total amount:</strong>
  <%= @sale.sale_total_amount %>
</p>

<p>
  <strong>Sale date:</strong>
  <%= @sale.sale_date %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>