SemesterProject-CSS-1/config/routes.rb
Rails.application.routes.draw do
  resources :sales
  resources :customers
  resources :quotes
  resources :employees
  resources :employees
  resources :inventories

  root 'employees#index'

end

SemesterProject-CSS-1/app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :quotes
  has_many :customers

  def full_name
    "#{first_name} #{middle_initial} #{last_name}"
  end

  def full_name_quote
    "#{first_name} #{middle_initial} #{last_name} || #{employee_class}"
  end

end

SemesterProject-CSS-1/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:first_name, :middle_initial, :last_name, :employee_class)
    end
end

SemesterProject-CSS-1/app/helpers/employees_helper.rb
module EmployeesHelper
end

SemesterProject-CSS-1/app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :middle_initial %><br>
    <%= f.text_field :middle_initial %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :employee_class %><br>
    <%= f.select :employee_class, [['Sales Person','Sales Person'],['Sales Manager','Sales Manager'],['Finance Manager','Finance Manager'],['Inventory Manager','Inventory Manager'],['Owner','Owner']]%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SemesterProject-CSS-1/app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

SemesterProject-CSS-1/app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Employees</h1>

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Initial</th>
      <th>Last Name</th>
      <th>Employee Classification</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.first_name %></td>
        <td><%= employee.middle_initial %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.employee_class %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div id="button">
<%= link_to 'New Employee', new_employee_path %>
</div>

SemesterProject-CSS-1/app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

SemesterProject-CSS-1/app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @employee.first_name %>
</p>

<p>
  <strong>Middle initial:</strong>
  <%= @employee.middle_initial %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @employee.last_name %>
</p>

<p>
  <strong>Employee class:</strong>
  <%= @employee.employee_class %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>