SemesterProject-CSS-1/config/routes.rb
Rails.application.routes.draw do
  resources :sales
  resources :customers
  resources :quotes
  resources :employees
  resources :employees
  resources :inventories

  root 'employees#index'

end

SemesterProject-CSS-1/app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :employee
  belongs_to :sale
  belongs_to :inventory

  def quote_info
    "#{customer} #{term} #{interest_rate} #{inventory}"
  end

end

SemesterProject-CSS-1/app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:employee, :customer, :inventory, :term, :interest_rate, :quote_status, :vehicle_total_price, :number_payment, :payment_amount)
    end
end

SemesterProject-CSS-1/app/helpers/quotes_helper.rb
module QuotesHelper
end

SemesterProject-CSS-1/app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :employee %><br>
    <%= f.collection_select :employee, Employee.all, :id, :full_name_quote %>
  </div>
  <div class="field">
    <%= f.label :customer %><br>
    <%= f.collection_select :customer, Customer.all, :id, :cust_full_name %>
  </div>
  <div class="field">
    <%= f.label :inventory %><br>
    <%= f.collection_select :inventory, Inventory.all, :id, :vehicle_info %>
  </div>
  <div class="field">
    <%= f.label :term %><br>
    <%= f.select :term, [['3 Years','36'],['4 Years','48'],['5 Years','60']] %>
  </div>
  <div class="field">
    <%= f.label :interest_rate %><br>
    <%= f.text_field :interest_rate %>
  </div>
  <div class="field">
    <%= f.label :quote_status %><br>
    <%= f.select :quote_status, [['Pending','Pending'],['Sold','Sold']] %>
  </div>
  <div class="field">
    <%= f.label :vehicle_total_price %><br>
    <%= f.text_field :vehicle_total_price %>
  </div>
  <div class="field">
    <%= f.label :number_payment %><br>
    <%= f.text_field :number_payment %>
  </div>
  <div class="field">
    <%= f.label :payment_amount %><br>
    <%= f.text_field :payment_amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SemesterProject-CSS-1/app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

SemesterProject-CSS-1/app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Quotes</h1>

<table>
  <thead>
    <tr>
      <th>Employee</th>
      <th>Customer</th>
      <th>Inventory</th>
      <th>Term</th>
      <th>Interest rate</th>
      <th>Quote status</th>
      <th>Vehicle Price</th>
      <th>Number of Payment</th>
      <th>Payment Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.employee.full_name_quote %></td>
        <td><%= quote.customer.cust_full_name %></td>
        <td><%= quote.inventory.vehicle_info %></td>
        <td><%= quote.term %></td>
        <td><%= quote.interest_rate %></td>
        <td><%= quote.quote_status %></td>
        <td><%= number_to_currency(quote.vehicle_total_price) %></td>
        <td><%= quote.number_payment %></td>
        <td><%= number_to_currency(quote.payment_amount) %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div id="button">
<%= link_to 'New Quote', new_quote_path %>
</div>

SemesterProject-CSS-1/app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

SemesterProject-CSS-1/app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employee:</strong>
  <%= @quote.employee.full_name_quote %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @quote.customer.cust_full_name %>
</p>

<p>
  <strong>Inventory:</strong>
  <%= @quote.inventory.vehicle_info %>
</p>

<p>
  <strong>Term:</strong>
  <%= f.select :term, [['3 Years','36'],['4 Years','48'],['5 Years','60']] %>
</p>

<p>
  <strong>Interest rate:</strong>
  <%= @quote.interest_rate %>
</p>

<p>
  <strong>Quote status:</strong>
  <%= f.select :quote_status, [['Pending','Pending'],['Sold','Sold']] %>
</p>

<p>
  <strong>Vehicle total price:</strong>
  <%= @quote.vehicle_total_price %>
</p>

<p>
  <strong>Number of Payments:</strong>
  <%= @quote.number_payment %>
</p>

<p>
  <strong>Payment amount:</strong>
  <%= @quote.payment_amount %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>