SemesterProject-CSS-1/config/routes.rb
Rails.application.routes.draw do
  resources :sales
  resources :customers
  resources :quotes
  resources :employees
  resources :employees
  resources :inventories

  root 'employees#index'

end

SemesterProject-CSS-1/app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :employee
  has_many :sales

  def cust_full_name
    "#{first_name} #{middle_initial} #{last_name}"
  end

  def self.search(search)
    where ['last_name LIKE ? OR first_name LIKE ?', "%#{search}%", "%#{search}%" ]
  end
end

SemesterProject-CSS-1/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.search(params[:search])
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:employee_rep, :first_name, :middle_initial, :last_name, :customer_status, :customer_address, :customer_city, :customer_zip, :customer_state)
    end
end

SemesterProject-CSS-1/app/helpers/customers_helper.rb
module CustomersHelper
end

SemesterProject-CSS-1/app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :employee_rep %><br>
    <%= f.text_field :employee_rep %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :middle_initial %><br>
    <%= f.text_field :middle_initial %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :customer_status %><br>
    <%= f.select :customer_status, [['Prospective','Prospective'],['Former','Former']] %>
  </div>
  <div class="field">
    <%= f.label :customer_address %><br>
    <%= f.text_field :customer_address %>
  </div>
  <div class="field">
    <%= f.label :customer_city %><br>
    <%= f.text_field :customer_city %>
  </div>
  <div class="field">
    <%= f.label :customer_zip %><br>
    <%= f.number_field :customer_zip %>
  </div>
  <div class="field">
    <%= f.label :customer_state %><br>
    <%= f.select :customer_state, [['AL','Alabama'],['AK','Alaska'],['AZ','Arizona'],['AR','Arkansas'],['CA','California'],['CO','Colorado'],['CT','Connecticut'],['DE','Delaware'],['DC','District of Columbia'],['FL','Florida'],['GA','Georgia'],['HI','Hawaii'],['ID','Idaho'],['IL','Illinois'],['IN','Indiana'],['IA','Iowa'],['KS','Kansas'],['KY','Kentucky'],['LA','Louisiana'],['ME','Maine'],['MD','Maryland'],['MA','Massachusetts'],['MI','Michigan'],['MN','Minnesota'],['MS','Mississippi'],['MO','Missouri'],['MT','Montana'],['NE','Nebraska'],['NV','Nevada'],['NH','New Hampshire'],['NJ','New Jersey'],['NM','New Mexico'],['NY','New York'],['NC','North Carolina'],['ND','North Dakota'],['OH','Ohio'],['OK','Oklahoma'],['OR','Oregon'],['PA','Pennsylvania'],['RI','Rhode Island'],['SC','South Carolina'],['SD','South Dakota'],['TN','Tennessee'],['TX','Texas'],['UT','Utah'],['VT','Vermont'],['VA','Virginia'],['WA','Washington'],['WV','West Virginia'],['WI','Wisconsin'],['WY','Wyoming']] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SemesterProject-CSS-1/app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

SemesterProject-CSS-1/app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag(customers_path, :method => "get", class: "navbar-form", id: "search-form") do %>
    <div class="input-append">
      <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search Customers" %>
      <%= submit_tag "Search", :name => nil %>
          </div>
	<% end %>

<h1>Listing Customers</h1>

<table>
  <thead>
    <tr>
      <th>Employee Representative</th>
      <th>First Name</th>
      <th>Initial</th>
      <th>Last Name</th>
      <th>Status</th>
      <th>Address</th>
      <th>City</th>
      <th>Zip Code</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.employee_rep %></td>
        <td><%= customer.first_name %></td>
        <td><%= customer.middle_initial %></td>
        <td><%= customer.last_name %></td>
        <td><%= customer.customer_status %></td>
        <td><%= customer.customer_address %></td>
        <td><%= customer.customer_city %></td>
        <td><%= customer.customer_zip %></td>
        <td><%= customer.customer_state %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div id="button">
<%= link_to 'New Customer', new_customer_path %>
</div>

SemesterProject-CSS-1/app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

SemesterProject-CSS-1/app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employee rep:</strong>
  <%= @customer.employee_rep %>
</p>

<p>
  <strong>First name:</strong>
  <%= @customer.first_name %>
</p>

<p>
  <strong>Middle initial:</strong>
  <%= @customer.middle_initial %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @customer.last_name %>
</p>

<p>
  <strong>Customer status:</strong>
  <%= @customer.customer_status %>
</p>

<p>
  <strong>Customer address:</strong>
  <%= @customer.customer_address %>
</p>

<p>
  <strong>Customer city:</strong>
  <%= @customer.customer_city %>
</p>

<p>
  <strong>Customer zip:</strong>
  <%= @customer.customer_zip %>
</p>

<p>
  <strong>Customer state:</strong>
  <%= @customer.customer_state %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>